"""add step column to reviews

Revision ID: 134738a46028
Revises: 8d79b32b6356
Create Date: 2026-08-11 22:28:30.406255

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "134738a46028"
down_revision: str | Sequence[str] | None = "8d79b32b6356"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("step", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "step")
    # ### end Alembic commands ###
