"""add index on review due and last_review

Revision ID: 35c10ee90fd3
Revises: cd3bb99a2724
Create Date: 2026-08-25 12:27:29.923676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c10ee90fd3'
down_revision: Union[str, Sequence[str], None] = 'cd3bb99a2724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reviews_due'), 'reviews', ['due'], unique=False)
    op.create_index(op.f('ix_reviews_last_review'), 'reviews', ['last_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_last_review'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_due'), table_name='reviews')
    # ### end Alembic commands ###
