"""add kind column to cards

Revision ID: 606c62aa4e7e
Revises: a2835d1212e7
Create Date: 2026-08-24 10:01:07.047834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606c62aa4e7e'
down_revision: Union[str, Sequence[str], None] = 'a2835d1212e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('kind', sa.String(length=10), server_default='word', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'kind')
    # ### end Alembic commands ###
