"""add rating column to reviews

Revision ID: 8154110d67de
Revises: ccab89041730
Create Date: 2026-08-24 19:19:29.458273

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '8154110d67de'
down_revision: str | Sequence[str] | None = 'ccab89041730'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
