"""add contexts column to cards

Revision ID: a2835d1212e7
Revises: 134738a46028
Create Date: 2026-08-12 16:57:13.044801

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2835d1212e7"
down_revision: str | Sequence[str] | None = "134738a46028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("contexts", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "contexts")
    # ### end Alembic commands ###
