"""add story content_cn and title_cn

Revision ID: cd3bb99a2724
Revises: 55d59e45a022
Create Date: 2026-08-25 12:22:53.517425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3bb99a2724'
down_revision: Union[str, Sequence[str], None] = '55d59e45a022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('content_cn', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('title_cn', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'title_cn')
    op.drop_column('stories', 'content_cn')
    # ### end Alembic commands ###
