"""add related_words to cards

Revision ID: fad563d280fa
Revises: 35c10ee90fd3
Create Date: 2026-08-25 13:36:11.234678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad563d280fa'
down_revision: Union[str, Sequence[str], None] = '35c10ee90fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('related_words', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'related_words')
    # ### end Alembic commands ###
